### ISSUE TITLE
Probably need a name change

### ISSUE THREAD

**Issue by tshort** [tshort/FunctionalModels.jl#84]
It fails the auto merge in the package registry (https://github.com/JuliaRegistries/General/pull/35819). The package name is too short. Options include:

* FunctionalModels
* FunctionalMTK

**Comment by xendo** [comment]
Without this change it's impossible to fetch from general repository. Quick workaround is to clone this repo and add Sims from local path:

`(@v1.7) pkg> add ~/Julia/Sims.jl`

**Comment by tshort** [comment]
Yeah. I'll work on this soon (probably over the weekend).

**Comment by tshort** [comment]
Done and registered
